#cloud-config
users:
  - name: web
    primary_group: web
    groups: wheel
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDhPZGfwjPKDdwaknLa7I5UE3PsL0bwJjkibM+g7k1Kq liam@glacier-lt

packages:
  - nginx
  - nmap
